// Generated by irubyc -- IronRuby's ahead-of-time packager.
//
// This file is the host of a compiled IronRuby application.  The Ruby sources
// are embedded in the assembly as managed resources and are served to the
// runtime through a PlatformAdaptationLayer overlay (sources.cs), so `require`,
// `load` and the main script read them out of the assembly rather than off
// disk.  The Ruby code itself is still compiled by IronRuby at run time,
// exactly as `ir app.rb` would compile it -- see irubyc --help.

using System;
using System.Collections.Generic;
using System.IO;
using IronRuby.Hosting;
using IronRuby.Runtime;
using Microsoft.Scripting;
using Microsoft.Scripting.Hosting;
using Microsoft.Scripting.Hosting.Shell;

namespace IronRuby.Compiled {

    /// <summary>
    /// RubyCommandLine.RunFile reaches for System.IO.File directly (MRI reports an unreadable
    /// script as a LoadError before the runtime is involved), so the main script needs its own
    /// route out of the assembly; `require` goes through the platform layer.
    /// </summary>
    internal sealed class EmbeddedCommandLine : RubyCommandLine {
        protected override int RunFile(string fileName) {
            byte[] bytes = EmbeddedSources.Read(fileName);
            if (bytes != null) {
                return RunFile(Engine.CreateScriptSource(
                    new EmbeddedContentProvider(bytes), fileName,
                    System.Text.Encoding.UTF8, SourceCodeKind.File));
            }
            return base.RunFile(fileName);
        }
    }

    internal sealed class CompiledApplication : RubyConsoleHost {
        protected override CommandLine CreateCommandLine() {
            return new EmbeddedCommandLine();
        }

        protected override ConsoleOptions ParseOptions(string[] args, ScriptRuntimeSetup runtimeSetup, LanguageSetup languageSetup) {
            // base sets HostType to RubyConsoleHost's own script host; replace it afterwards.
            var options = base.ParseOptions(args, runtimeSetup, languageSetup);
            runtimeSetup.HostType = typeof(EmbeddedScriptHost);
            return options;
        }

        [STAThread]
        [RubyStackTraceHidden]
        public static int Main(string[] args) {
            RubyContext.AlternativeParser = IronRuby.Prism.PrismAstBridge.Parse;

            var argv = new List<string>();

            string lib = Path.Combine(AppContext.BaseDirectory, "Lib");
            if (Directory.Exists(lib)) {
                var libraries = new List<string>();
                foreach (var dir in new[] {
                    Path.Combine(lib, "ironruby"),
                    Path.Combine(lib, "ruby", "4.0"),
                    Path.Combine(lib, "ruby", "1.9.1"),
                }) {
                    if (Directory.Exists(dir)) libraries.Add(dir);
                }
                if (libraries.Count > 0) {
                    argv.Add("-X:StdLib=" + string.Join(Path.PathSeparator.ToString(), libraries));
                }
            }

            // irubyc --no-stdlib leaves out Lib/ruby, which is where gem_prelude.rb lives
            // and where RubyGems would look; without it the runtime must not try to boot
            // gems. Core Ruby still works, `require` of a library does not.
            if (!Directory.Exists(Path.Combine(lib, "ruby", "4.0"))) {
                argv.Add("--disable-gems");
            }

            // The virtual source root goes on $LOAD_PATH so that the embedded files can
            // require each other by name, the way -I<app dir> would on a source tree.
            // The main script's own directory goes on too, so that --prefix, and a main
            // script sitting in a subdirectory, do not break its requires.
            argv.Add("-I" + EmbeddedSources.Root);
            string mainDir = Path.GetDirectoryName(EmbeddedSources.MainFullPath);
            if (mainDir != null && !string.Equals(mainDir, EmbeddedSources.Root, StringComparison.Ordinal)) {
                argv.Add("-I" + mainDir);
            }
            argv.Add(EmbeddedSources.MainFullPath);
            argv.AddRange(args);

            return new CompiledApplication().Run(argv.ToArray());
        }
    }
}
