// Generated by irubyc --library -- the bootstrap of a single-DLL IronRuby library.
//
// This DLL carries IronRuby, the DLR, their native libraries, the Ruby standard
// library and the program's Ruby sources as one embedded zip.  .NET has no
// single-file mode for a class library, so it unpacks itself: on first use the
// payload is extracted to a per-content cache directory, and assembly and
// native-library resolvers serve IronRuby from there.
//
// ORDER MATTERS.  Nothing in this file may name an IronRuby or DLR type in a
// base type, an interface, a value-type field or anything else the runtime
// loads with the type itself: a plugin host enumerates this assembly's types
// (Assembly.GetTypes()) before any of its code runs, and IronRuby cannot be
// found until the resolvers below are installed.  Method signatures are fine:
// they are only resolved when a caller is JIT-compiled, and by then the module
// initializer has run.  Everything that derives from IronRuby lives in the
// payload's <Name>.RubyHost assembly (libraryhost.cs, sources.cs).

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using Microsoft.Scripting.Hosting;

namespace IronRuby.Embedded {

    /// <summary>
    /// The IronRuby this library carries, for the C# code compiled into it (irubyc --cs).
    /// </summary>
    public static class RubyHost {
        /// <summary>The main Ruby file, relative to <see cref="SourceRoot"/>.</summary>
        public const string MainScript = @"@@MAIN_PATH@@";

        /// <summary>
        /// The directory the payload was extracted to (IronRuby's assemblies, native libraries
        /// and Lib/).  Extracts it on first use.
        /// </summary>
        public static string ExtractDirectory {
            get { return Bootstrap.EnsureExtracted(); }
        }

        /// <summary>
        /// The virtual directory the embedded Ruby files appear under.  `require`, `load`,
        /// require_relative and File.read see them there; the directory is not on disk.
        /// </summary>
        public static string SourceRoot {
            get { Bootstrap.EnsureExtracted(); return CoreSourceRoot(); }
        }

        /// <summary>
        /// Creates a Ruby engine with the embedded Ruby files and the standard library on the
        /// load path and the core library booted.  This library's own assembly and the host
        /// assemblies it was compiled against (irubyc --reference) are visible to Ruby, so their
        /// namespaces can be named directly (Host::Api::...).
        /// </summary>
        public static ScriptEngine CreateEngine() {
            return CreateEngine(null);
        }

        /// <param name="configure">Adjusts the Ruby language setup before the runtime starts.</param>
        public static ScriptEngine CreateEngine(Action<LanguageSetup> configure) {
            return CreateEngine(null, configure);
        }

        /// <param name="configureRuntime">
        /// Adjusts the runtime setup, e.g. <c>setup.PrivateBinding = true</c> to let Ruby call
        /// non-public CLR members - protected ones included, which IronRuby otherwise only lets a
        /// Ruby subclass call.
        /// </param>
        /// <param name="configure">Adjusts the Ruby language setup before the runtime starts.</param>
        public static ScriptEngine CreateEngine(Action<ScriptRuntimeSetup> configureRuntime, Action<LanguageSetup> configure) {
            string dir = Bootstrap.EnsureExtracted();
            return CoreCreateEngine(Path.Combine(dir, "Lib"), Bootstrap.HostAssemblies(), configureRuntime, configure);
        }

        /// <summary>
        /// Runs one of the embedded Ruby files (a path relative to <see cref="SourceRoot"/>, as
        /// given to irubyc) and returns the value of its last expression.
        /// </summary>
        public static object Run(ScriptEngine engine, string path, ScriptScope scope) {
            return CoreRun(engine, path, scope);
        }

        public static object Run(ScriptEngine engine, string path) {
            return CoreRun(engine, path, null);
        }

        /// <summary>Runs the main Ruby file; see <see cref="Run(ScriptEngine, string, ScriptScope)"/>.</summary>
        public static object RunMain(ScriptEngine engine, ScriptScope scope) {
            return CoreRun(engine, MainScript, scope);
        }

        // The payload's RubyHost assembly is only named inside these, so it is only resolved
        // when one of them is JIT-compiled - after EnsureExtracted.
        [MethodImpl(MethodImplOptions.NoInlining)]
        private static string CoreSourceRoot() {
            return IronRuby.Compiled.RubyHostCore.SourceRoot;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static ScriptEngine CoreCreateEngine(string lib, Assembly[] hostAssemblies,
                                                     Action<ScriptRuntimeSetup> configureRuntime, Action<LanguageSetup> configure) {
            return IronRuby.Compiled.RubyHostCore.CreateEngine(lib, hostAssemblies, configureRuntime, configure);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static object CoreRun(ScriptEngine engine, string path, ScriptScope scope) {
            Bootstrap.EnsureExtracted();
            return IronRuby.Compiled.RubyHostCore.Run(engine, path, scope);
        }
    }

    internal static class Bootstrap {
        private const string PayloadResource = "irubyc.payload.zip";

        // Names the extraction directory: <assembly>-<first 16 hex digits of the payload's SHA-256>.
        // A rebuilt library with different content extracts next to the old one, never over it.
        internal const string ExtractName = @"@@EXTRACT_NAME@@";
        private const string CompleteMarker = ".irubyc-complete";

        // What the payload was built for: its native libraries are this platform's only.
        private const string BuildRid = @"@@BUILD_RID@@";
        private const string BuildOS = @"@@BUILD_OS@@";
        private const string BuildArchitecture = @"@@BUILD_ARCH@@";

        // The managed assemblies in the payload (simple names); only these are resolved here.
        private static readonly string[] PayloadAssemblies = new string[] {
@@PAYLOAD_ASSEMBLIES@@
        };

        // Assemblies the host provides (irubyc --reference): handed to Ruby, never bundled.
        private static readonly string[] HostReferences = new string[] {
@@HOST_REFERENCES@@
        };

        private static readonly object Gate = new object();
        private static readonly Dictionary<string, Assembly> Loaded =
            new Dictionary<string, Assembly>(StringComparer.OrdinalIgnoreCase);
        private static HashSet<string> _payloadNames;
        private static AssemblyLoadContext _context;
        private static string _directory;

        private static readonly bool Tracing = Environment.GetEnvironmentVariable("IRUBYC_TRACE") == "1";

        /// <summary>
        /// Runs before any other code of this assembly: before the host's first call into it and
        /// before the first IronRuby type is needed.  Only installs the resolvers - no I/O; the
        /// payload is extracted when something first needs it.
        /// </summary>
#pragma warning disable CA2255 // a library's module initializer is exactly what is meant here
        [ModuleInitializer]
#pragma warning restore CA2255
        internal static void Initialize() {
            Install();
        }

        internal static void Install() {
            lock (Gate) {
                if (_context != null) return;
                _payloadNames = new HashSet<string>(PayloadAssemblies, StringComparer.OrdinalIgnoreCase);

                // The context this library was loaded into: its own one when the host used
                // Assembly.LoadFile or a plugin context, the default one otherwise.  IronRuby is
                // loaded into the same one, so two libraries in one process each have their own.
                _context = AssemblyLoadContext.GetLoadContext(typeof(Bootstrap).Assembly) ?? AssemblyLoadContext.Default;
                _context.Resolving += OnResolving;
                _context.ResolvingUnmanagedDll += OnResolvingUnmanagedDll;
                // Fallback for lookups that do not start in that context's Resolving event.
                AppDomain.CurrentDomain.AssemblyResolve += OnAppDomainAssemblyResolve;
                Trace("installed resolvers on " + Describe(_context));
            }
        }

        internal static Assembly[] HostAssemblies() {
            var result = new List<Assembly> { typeof(Bootstrap).Assembly };
            foreach (string name in HostReferences) {
                try {
                    result.Add(_context.LoadFromAssemblyName(new AssemblyName(name)));
                } catch (Exception e) {
                    Trace("host reference " + name + " not available: " + e.Message);
                }
            }
            return result.ToArray();
        }

        #region Resolvers

        private static Assembly OnResolving(AssemblyLoadContext context, AssemblyName name) {
            Trace("AssemblyLoadContext.Resolving: " + name.Name);
            return Load(name);
        }

        private static Assembly OnAppDomainAssemblyResolve(object sender, ResolveEventArgs args) {
            // Every library in the process has one of these; answer only for this one's context.
            AssemblyLoadContext requester = args.RequestingAssembly != null
                ? AssemblyLoadContext.GetLoadContext(args.RequestingAssembly)
                : AssemblyLoadContext.CurrentContextualReflectionContext;
            if (requester != _context) return null;
            Trace("AppDomain.AssemblyResolve: " + args.Name);
            return Load(new AssemblyName(args.Name));
        }

        private static Assembly Load(AssemblyName name) {
            if (name.Name == null || !_payloadNames.Contains(name.Name)) return null;
            lock (Gate) {
                Assembly assembly;
                if (Loaded.TryGetValue(name.Name, out assembly)) return assembly;
                string path = Path.Combine(EnsureExtracted(), name.Name + ".dll");
                assembly = _context.LoadFromAssemblyPath(path);
                Loaded[name.Name] = assembly;
                Trace("loaded " + path);
                return assembly;
            }
        }

        private static IntPtr OnResolvingUnmanagedDll(Assembly requester, string name) {
            if (AssemblyLoadContext.GetLoadContext(requester) != _context) return IntPtr.Zero;
            string dir = EnsureExtracted();
            foreach (string candidate in NativeFileNames(name)) {
                string path = Path.Combine(dir, candidate);
                IntPtr handle;
                if (File.Exists(path) && NativeLibrary.TryLoad(path, out handle)) {
                    Trace("ResolvingUnmanagedDll: " + name + " -> " + path);
                    return handle;
                }
            }
            Trace("ResolvingUnmanagedDll: " + name + " not in the payload");
            return IntPtr.Zero;
        }

        // DllImport("prism") means libprism.so here, libprism.dll or prism.dll on Windows.
        private static IEnumerable<string> NativeFileNames(string name) {
            string suffix = OperatingSystem.IsWindows() ? ".dll" : OperatingSystem.IsMacOS() ? ".dylib" : ".so";
            string file = Path.GetFileName(name);
            yield return file;
            if (!file.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)) {
                yield return file + suffix;
                if (!file.StartsWith("lib", StringComparison.Ordinal)) {
                    yield return "lib" + file + suffix;
                }
            }
        }

        #endregion

        #region Extraction

        /// <summary>
        /// The extracted payload's directory, extracting it on first use.  Extraction goes to a
        /// private temporary directory that is then renamed into place in one step, so a
        /// process never sees half a payload, and two processes extracting at once both end
        /// up using whichever finished first.
        /// </summary>
        internal static string EnsureExtracted() {
            lock (Gate) {
                if (_directory != null) return _directory;
                CheckPlatform();

                string root = ExtractRoot();
                string target = Path.Combine(root, ExtractName);
                if (!IsComplete(target)) {
                    var watch = Stopwatch.StartNew();
                    bool won = Extract(target);
                    Trace((won ? "extracted to " : "extracted, but another process was first: using ") +
                          target + " (" + watch.ElapsedMilliseconds + " ms)");
                } else {
                    Trace("reusing " + target);
                }
                _directory = target;
                return _directory;
            }
        }

        // IRUBYC_EXTRACT_BASE_DIR, the way the .NET bundler has DOTNET_BUNDLE_EXTRACT_BASE_DIR;
        // otherwise a per-user directory under the temporary directory.
        private static string ExtractRoot() {
            string configured = Environment.GetEnvironmentVariable("IRUBYC_EXTRACT_BASE_DIR");
            if (!string.IsNullOrEmpty(configured)) {
                CreatePrivateDirectory(configured);
                return Path.GetFullPath(configured);
            }
            // Windows' temporary directory is per user already; /tmp is shared.
            string name = OperatingSystem.IsWindows() ? "irubyc" : "irubyc-" + SafeUserName();
            string root = Path.Combine(Path.GetTempPath(), name);
            CreatePrivateDirectory(root);
            return root;
        }

        private static string SafeUserName() {
            string user;
            try { user = Environment.UserName; } catch { user = null; }
            if (string.IsNullOrEmpty(user)) return "user";
            foreach (char c in Path.GetInvalidFileNameChars()) user = user.Replace(c, '_');
            return user;
        }

        private static void CreatePrivateDirectory(string path) {
            if (OperatingSystem.IsWindows()) {
                Directory.CreateDirectory(path);
                return;
            }
            if (!Directory.Exists(path)) {
                Directory.CreateDirectory(path, UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute);
            }
            // Code is loaded from here: refuse a directory other users can write to.
            UnixFileMode mode = File.GetUnixFileMode(path);
            if ((mode & (UnixFileMode.GroupWrite | UnixFileMode.OtherWrite)) != 0 &&
                (mode & UnixFileMode.StickyBit) == 0) {
                throw new UnauthorizedAccessException(
                    "irubyc: the extraction directory " + path + " is writable by other users; " +
                    "set IRUBYC_EXTRACT_BASE_DIR to a private directory");
            }
        }

        private static bool IsComplete(string dir) {
            try {
                string marker = Path.Combine(dir, CompleteMarker);
                if (!File.Exists(marker) || File.ReadAllText(marker).Trim() != ExtractName) return false;
                foreach (string name in PayloadAssemblies) {
                    if (!File.Exists(Path.Combine(dir, name + ".dll"))) return false;
                }
                return true;
            } catch (IOException) {
                return false;
            } catch (UnauthorizedAccessException) {
                return false;
            }
        }

        // True when this process's copy was the one moved into place.
        private static bool Extract(string target) {
            string temp = target + ".tmp-" + Environment.ProcessId + "-" + Guid.NewGuid().ToString("N").Substring(0, 8);
            try {
                using (Stream payload = typeof(Bootstrap).Assembly.GetManifestResourceStream(PayloadResource)) {
                    if (payload == null) {
                        throw new InvalidOperationException("irubyc: the library has no embedded payload (" + PayloadResource + ")");
                    }
                    using (var zip = new ZipArchive(payload, ZipArchiveMode.Read)) {
                        zip.ExtractToDirectory(temp);
                    }
                }
                File.WriteAllText(Path.Combine(temp, CompleteMarker), ExtractName);

                for (int attempt = 0; ; attempt++) {
                    try {
                        Directory.Move(temp, target);
                        return true;
                    } catch (IOException) when (Directory.Exists(target)) {
                        // Another process got there first: use its copy.
                        if (IsComplete(target)) {
                            return false;
                        }
                        // Something incomplete is in the way (files deleted by hand, say): move it
                        // aside - atomically, so a concurrent extractor sees it gone or whole - and
                        // try again.
                        if (attempt >= 3) throw;
                        string stale = target + ".stale-" + Guid.NewGuid().ToString("N").Substring(0, 8);
                        try {
                            Directory.Move(target, stale);
                            TryDelete(stale);
                        } catch (IOException) {
                            // lost a race; look again
                        }
                    }
                }
            } finally {
                TryDelete(temp);
            }
        }

        private static void TryDelete(string dir) {
            try {
                if (Directory.Exists(dir)) Directory.Delete(dir, true);
            } catch (IOException) {
            } catch (UnauthorizedAccessException) {
            }
        }

        private static void CheckPlatform() {
            string os = OperatingSystem.IsWindows() ? "windows" : OperatingSystem.IsMacOS() ? "osx" : OperatingSystem.IsLinux() ? "linux" : "other";
            string arch = RuntimeInformation.ProcessArchitecture.ToString();
            if (os != BuildOS || arch != BuildArchitecture) {
                throw new PlatformNotSupportedException(
                    "irubyc: " + typeof(Bootstrap).Assembly.GetName().Name + ".dll was built on " + BuildRid +
                    " and carries that platform's native libraries (libprism, sqlite); this process is " +
                    os + "/" + arch + ". Run irubyc --library on the target platform to build it for there.");
            }
        }

        #endregion

        private static string Describe(AssemblyLoadContext context) {
            return (context == AssemblyLoadContext.Default ? "the default context" : "context '" + context.Name + "'");
        }

        private static void Trace(string message) {
            if (Tracing) {
                Console.Error.WriteLine("[irubyc " + typeof(Bootstrap).Assembly.GetName().Name + "] " + message);
            }
        }
    }
}
