// Generated by irubyc --library -- the IronRuby half of a single-DLL library.
//
// This assembly is not what the host loads.  It travels inside the library's
// payload and is extracted and loaded by the library's bootstrap (library.cs)
// only after its assembly resolvers are in place, because every type here
// derives from or refers to IronRuby and the DLR: had these types been in the
// library itself, a host that enumerates the library's types before anything
// else (Assembly.GetTypes(), as plugin loaders do) would fail to load them.

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using IronRuby;
using IronRuby.Runtime;
using Microsoft.Scripting;
using Microsoft.Scripting.Hosting;

namespace IronRuby.Compiled {

    public static class RubyHostCore {
        private static readonly object Gate = new object();

        public static string SourceRoot {
            get { return EmbeddedSources.Root; }
        }

        public static string MainFullPath {
            get { return EmbeddedSources.MainFullPath; }
        }

        /// <summary>
        /// A Ruby engine the way `ir` would set one up: prism as the parser, the extracted
        /// standard library on $LOAD_PATH, the core prelude (and RubyGems, when the library
        /// carries the standard library) booted, and the embedded sources on $LOAD_PATH under
        /// their virtual root.
        /// </summary>
        public static ScriptEngine CreateEngine(string libDir, Assembly[] hostAssemblies,
                                                Action<ScriptRuntimeSetup> configureRuntime, Action<LanguageSetup> configure) {
            lock (Gate) {
                // One per copy of IronRuby, i.e. per library: every library loads its own.
                RubyContext.AlternativeParser = IronRuby.Prism.PrismAstBridge.Parse;
            }

            var runtimeSetup = new ScriptRuntimeSetup();
            runtimeSetup.HostType = typeof(EmbeddedScriptHost);

            var language = Ruby.CreateRubySetup();
            bool stdlib = Directory.Exists(Path.Combine(libDir, "ruby", "4.0"));

            var searchPaths = new List<string> { EmbeddedSources.Root };
            string mainDir = Path.GetDirectoryName(EmbeddedSources.MainFullPath);
            if (mainDir != null && !string.Equals(mainDir, EmbeddedSources.Root, StringComparison.Ordinal)) {
                searchPaths.Add(mainDir);
            }
            language.Options["SearchPaths"] = searchPaths;
            language.Options["StandardLibrary"] = libDir;
            language.Options["ApplicationBase"] = Path.GetDirectoryName(libDir);
            // gem_prelude.rb boots RubyGems and then the core layer (ruby4.rb); without the
            // standard library there is no RubyGems to boot, only the core layer.
            language.Options["RequiredPaths"] = new List<string> { stdlib ? "gem_prelude.rb" : "ruby4.rb" };

            if (configure != null) {
                configure(language);
            }
            runtimeSetup.LanguageSetups.Add(language);
            if (configureRuntime != null) {
                configureRuntime(runtimeSetup);
            }

            var runtime = new ScriptRuntime(runtimeSetup);
            if (hostAssemblies != null) {
                foreach (var assembly in hostAssemblies) {
                    if (assembly != null) runtime.LoadAssembly(assembly);
                }
            }
            var engine = Ruby.GetEngine(runtime);

            // The prelude is required by the top-level scope of the *main* program, which a
            // hosted engine never runs: ScriptSource.Execute makes a plain one.  Running an
            // empty main program boots it once, and everything run afterwards sees it.
            engine.CreateScriptSourceFromString("", "<irubyc>", SourceCodeKind.File).ExecuteProgram();
            return engine;
        }

        /// <summary>
        /// Runs an embedded file (a path relative to the source root, as irubyc embedded it)
        /// and returns the value of its last expression.
        /// </summary>
        public static object Run(ScriptEngine engine, string path, ScriptScope scope) {
            if (engine == null) throw new ArgumentNullException("engine");
            if (path == null) throw new ArgumentNullException("path");
            string full = Path.GetFullPath(Path.Combine(EmbeddedSources.Root, path));
            byte[] bytes = EmbeddedSources.Read(full);
            if (bytes == null) {
                throw new FileNotFoundException("irubyc: " + path + " is not among the embedded Ruby files", full);
            }
            var source = engine.CreateScriptSource(new EmbeddedContentProvider(bytes), full,
                System.Text.Encoding.UTF8, SourceCodeKind.File);
            return scope != null ? source.Execute(scope) : source.Execute();
        }
    }
}
