<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>IronRuby.Libraries.Yaml</AssemblyName>
    <RootNamespace>IronRuby.StandardLibrary.Yaml</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ruby\Ruby.csproj" />
    <ProjectReference Include="..\Libraries\IronRuby.Libraries.csproj" />
    <ProjectReference Include="$(DlrSourceDir)\Microsoft.Scripting\Microsoft.Scripting.csproj" />
    <ProjectReference Include="$(DlrSourceDir)\Microsoft.Dynamic\Microsoft.Dynamic.csproj" />
  </ItemGroup>
</Project>
