#!/bin/bash
# Regenerate Src/Libraries/Initializers.Generated.cs (see
# Src/ClassInitGenerator/README.md for what the file is and why it matters).
#
# Chicken-and-egg problem this script exists to solve: the generator reflects
# over IronRuby.Libraries.dll, but that assembly cannot be built while the
# checked-in Initializers.Generated.cs still refers to the *old* shape of
# whatever [RubyMethod]/[RubyClass] you just changed.  So the file is first
# replaced with an empty-but-valid skeleton (one do-nothing initializer per
# library namespace), the assembly is built from that, and the real file is
# then generated by reflecting over the result.
#
# Usage:  ./regen-initializers.sh
#         DLR_SOURCE_DIR=/path/to/dlr/src/core ./regen-initializers.sh
#
# If you add a new library namespace, add it to LIBS below *and* to the list in
# Src/ClassInitGenerator/README.md.  Omitting an existing namespace silently
# unregisters everything in it.
set -e
cd "$(dirname "$0")"
export DOTNET_ROOT=${DOTNET_ROOT:-/usr/local/dotnet}
DOTNET="$DOTNET_ROOT/dotnet"
DLR=${DLR_SOURCE_DIR:-../dlr/src/core}
GEN=Src/Libraries/Initializers.Generated.cs
LIBS="IronRuby.Builtins;IronRuby.StandardLibrary.Threading;IronRuby.StandardLibrary.Sockets;IronRuby.StandardLibrary.OpenSsl;IronRuby.StandardLibrary.Digest;IronRuby.StandardLibrary.Zlib;IronRuby.StandardLibrary.StringIO;IronRuby.StandardLibrary.StringScanner;IronRuby.StandardLibrary.Enumerator;IronRuby.StandardLibrary.FunctionControl;IronRuby.StandardLibrary.FileControl;IronRuby.StandardLibrary.BigDecimal;IronRuby.StandardLibrary.Iconv;IronRuby.StandardLibrary.ParseTree;IronRuby.StandardLibrary.Open3;IronRuby.StandardLibrary.Win32API;IronRuby.StandardLibrary.Json;IronRuby.StandardLibrary.Date"

cp "$GEN" /tmp/Initializers.Generated.bak.cs
python3 - "$GEN" "$LIBS" <<'PY'
import sys
path, libs = sys.argv[1], sys.argv[2]
out = ['// Skeleton written by regen-initializers.sh; overwritten by the generator below.\r']
names = libs.split(';')
for n in names:
    out.append(f'[assembly: IronRuby.Runtime.RubyLibraryAttribute(typeof({n}.{n.split(".")[-1]}LibraryInitializer))]\r')
out.append('\r')
for n in names:
    cls = n.split('.')[-1] + 'LibraryInitializer'
    out += [f'namespace {n} {{\r',
            f'    public sealed class {cls} : IronRuby.Builtins.LibraryInitializer {{\r',
            '        protected override void LoadModules() {\r',
            '        }\r',
            '    }\r',
            '}\r',
            '\r']
open(path, 'wb').write('\n'.join(out).encode('utf-8'))
PY

# Note the build status is taken from dotnet's own exit code, not from grepping
# its output: `dotnet build | grep -E 'error|Build succeeded'` succeeds when the
# build FAILS, because the error lines match the pattern too. That let a broken
# build through to the generator, which then reflected over a stale
# IronRuby.Libraries.dll and silently regenerated the *previous* registrations.
if ! BUILD_LOG=$($DOTNET build Src/ClassInitGenerator/ClassInitGenerator.csproj -p:DlrSourceDir="$DLR" 2>&1); then
  echo "$BUILD_LOG" | grep -E 'error' | sort -u
  cp /tmp/Initializers.Generated.bak.cs "$GEN"
  echo "generator build failed; $GEN restored" >&2
  exit 1
fi
echo "$BUILD_LOG" | grep -E 'Build succeeded'

D=Src/ClassInitGenerator/bin/Debug/net8.0
$DOTNET $D/ClassInitGenerator.dll $D/IronRuby.Libraries.dll "/libraries:$LIBS" /out:/tmp/Initializers.Generated.new.cs > /dev/null
# the checked-in file uses CRLF
python3 -c "
d = open('/tmp/Initializers.Generated.new.cs','rb').read().replace(b'\r\n', b'\n').replace(b'\n', b'\r\n')
open('$GEN','wb').write(d)
print('wrote $GEN:', len(d), 'bytes')
"
