#!/bin/bash
# Regenerate Src/Libraries/Initializers.Generated.cs (see
# Src/ClassInitGenerator/README.md for what the file is and why it matters).
#
# Chicken-and-egg problem this script exists to solve: the generator reflects
# over IronRuby.Libraries.dll, but that assembly cannot be built while the
# checked-in Initializers.Generated.cs still refers to the *old* shape of
# whatever [RubyMethod]/[RubyClass] you just changed.  So the file is first
# replaced with an empty-but-valid skeleton (one do-nothing initializer per
# library namespace), the assembly is built from that, and the real file is
# then generated by reflecting over the result.
#
# Usage:  ./regen-initializers.sh
#         DLR_SOURCE_DIR=/path/to/dlr/src/core ./regen-initializers.sh
#         IR_CONFIG=Release ./regen-initializers.sh
#
# IR_CONFIG picks the configuration the intermediate assemblies are built in - it only
# decides which bin/<config> tree this script churns, since what the generator writes is
# reflected from the [RubyMethod]/[RubyClass] attributes and is the same either way.  Use
# the configuration you are otherwise building, so this does not leave a second, stale one
# behind (and, for Release, so the build it repairs on the way out is the one you run).
#
# If you add a new library namespace, add it to LIBS below *and* to the list in
# Src/ClassInitGenerator/README.md.  Omitting an existing namespace silently
# unregisters everything in it.
set -e
cd "$(dirname "$0")"

# This script rebuilds the in-place assemblies - it has to, since the generator reflects over
# IronRuby.Libraries.dll - and for part of its run the generated file is an empty skeleton, so
# the build it leaves behind mid-way has nothing registered. A spec sweep running against that
# build measures nonsense, and the corruption is silent. Refuse rather than rely on remembering.
# Matched on the interpreter process itself (comm == ir) rather than on any command line
# mentioning mspec-run, which would also match the shell that is invoking this script. Only
# runs of this tree's own binary count: other worktrees have their own build.
BIN="$(pwd -P)/Src/Console/bin/"
if ps -eo comm=,args= | awk -v bin="$BIN" '$1 == "ir" && /mspec-run/ && index($2, bin) == 1 { found = 1 } END { exit !found }'; then
  echo "refusing to run: an mspec sweep is using the in-place build" >&2
  echo "wait for it to finish, or stop it first (ps -eo comm=,args= | grep mspec-run)" >&2
  exit 1
fi
export DOTNET_ROOT=${DOTNET_ROOT:-/usr/local/dotnet}
DOTNET="$DOTNET_ROOT/dotnet"
: "${IR_CONFIG:=Debug}"
# The generator only reflects over attributes, so the framework it runs on does not change
# what it writes; IR_TFM just says which of the multi-targeted outputs to run.
: "${IR_TFM:=net8.0}"
DLR=${DLR_SOURCE_DIR:-../dlr/src/core}
GEN=Src/Libraries/Initializers.Generated.cs
LIBS="IronRuby.Builtins;IronRuby.StandardLibrary.Threading;IronRuby.StandardLibrary.Sockets;IronRuby.StandardLibrary.OpenSsl;IronRuby.StandardLibrary.Digest;IronRuby.StandardLibrary.Zlib;IronRuby.StandardLibrary.StringIO;IronRuby.StandardLibrary.StringScanner;IronRuby.StandardLibrary.Enumerator;IronRuby.StandardLibrary.FunctionControl;IronRuby.StandardLibrary.FileControl;IronRuby.StandardLibrary.BigDecimal;IronRuby.StandardLibrary.Iconv;IronRuby.StandardLibrary.ParseTree;IronRuby.StandardLibrary.Open3;IronRuby.StandardLibrary.Win32API;IronRuby.StandardLibrary.Json;IronRuby.StandardLibrary.Date;IronRuby.StandardLibrary.Syslog;IronRuby.StandardLibrary.Coverage;IronRuby.StandardLibrary.Ripper;IronRuby.StandardLibrary.Termios;IronRuby.StandardLibrary.Prism;IronRuby.StandardLibrary.Sqlite3;IronRuby.StandardLibrary.Nokogiri;IronRuby.StandardLibrary.Fiddle;IronRuby.StandardLibrary.WebSocketDriver;IronRuby.StandardLibrary.MessagePack;IronRuby.StandardLibrary.Oj;IronRuby.StandardLibrary.BCrypt;IronRuby.StandardLibrary.Nio4r;IronRuby.StandardLibrary.Puma"

cp "$GEN" /tmp/Initializers.Generated.bak.cs
python3 - "$GEN" "$LIBS" <<'PY'
import sys
path, libs = sys.argv[1], sys.argv[2]
out = ['// Skeleton written by regen-initializers.sh; overwritten by the generator below.\r']
names = libs.split(';')
for n in names:
    out.append(f'[assembly: IronRuby.Runtime.RubyLibraryAttribute(typeof({n}.{n.split(".")[-1]}LibraryInitializer))]\r')
out.append('\r')
for n in names:
    cls = n.split('.')[-1] + 'LibraryInitializer'
    out += [f'namespace {n} {{\r',
            f'    public sealed class {cls} : IronRuby.Builtins.LibraryInitializer {{\r',
            '        protected override void LoadModules() {\r',
            '        }\r',
            '    }\r',
            '}\r',
            '\r']
open(path, 'wb').write('\n'.join(out).encode('utf-8'))
PY

# Note the build status is taken from dotnet's own exit code, not from grepping
# its output: `dotnet build | grep -E 'error|Build succeeded'` succeeds when the
# build FAILS, because the error lines match the pattern too. That let a broken
# build through to the generator, which then reflected over a stale
# IronRuby.Libraries.dll and silently regenerated the *previous* registrations.
if ! BUILD_LOG=$($DOTNET build Src/ClassInitGenerator/ClassInitGenerator.csproj -c "$IR_CONFIG" -p:DlrSourceDir="$DLR" 2>&1); then
  echo "$BUILD_LOG" | grep -E 'error' | sort -u
  cp /tmp/Initializers.Generated.bak.cs "$GEN"
  echo "generator build failed; $GEN restored" >&2
  exit 1
fi
echo "$BUILD_LOG" | grep -E 'Build succeeded'

D=Src/ClassInitGenerator/bin/$IR_CONFIG/$IR_TFM
$DOTNET $D/ClassInitGenerator.dll $D/IronRuby.Libraries.dll "/libraries:$LIBS" /out:/tmp/Initializers.Generated.new.cs > /dev/null
# the checked-in file uses CRLF
python3 -c "
d = open('/tmp/Initializers.Generated.new.cs','rb').read().replace(b'\r\n', b'\n').replace(b'\n', b'\r\n')
open('$GEN','wb').write(d)
print('wrote $GEN:', len(d), 'bytes')
"
