<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>IronRuby.Tests</AssemblyName>
    <RootNamespace>IronRuby.Tests</RootNamespace>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ruby\Ruby.csproj" />
    <ProjectReference Include="..\Libraries\IronRuby.Libraries.csproj" />
    <ProjectReference Include="..\Libraries.Yaml\IronRuby.Libraries.Yaml.csproj" />
    <ProjectReference Include="$(DlrSourceDir)\Microsoft.Scripting\Microsoft.Scripting.csproj" />
    <ProjectReference Include="$(DlrSourceDir)\Microsoft.Dynamic\Microsoft.Dynamic.csproj" />
  </ItemGroup>
</Project>
