# -*- encoding: utf-8 -*-
# stub: bcrypt 3.1.22 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "bcrypt".freeze
  s.version = "3.1.22"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "OpenBSD bcrypt password hashing; bcrypt_ext in C#.  Provided by IronRuby itself.".freeze
  s.summary = "OpenBSD bcrypt password hashing; bcrypt_ext in C#".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/bcrypt.rb".freeze,
    "lib/bcrypt/engine.rb".freeze,
    "lib/bcrypt/error.rb".freeze,
    "lib/bcrypt/password.rb".freeze,
    "lib/bcrypt_ext.rb".freeze,
  ]
end
