# -*- encoding: utf-8 -*-
# stub: bigdecimal 4.0.1 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "bigdecimal".freeze
  s.version = "4.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Arbitrary-precision decimal arithmetic.  Provided by IronRuby itself.".freeze
  s.summary = "Arbitrary-precision decimal arithmetic".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/bigdecimal.rb".freeze,
    "lib/bigdecimal/util.rb".freeze,
    "lib/bigdecimal/jacobian.rb".freeze,
    "lib/bigdecimal/ludcmp.rb".freeze,
    "lib/bigdecimal/math.rb".freeze,
    "lib/bigdecimal/newton.rb".freeze,
  ]
end
