# -*- encoding: utf-8 -*-
# stub: cgi 0.5.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "cgi".freeze
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "CGI.escape and friends - Ruby 4.0's cgi/escape, not the full CGI class.  Provided by IronRuby itself.".freeze
  s.summary = "CGI.escape and friends - Ruby 4.0's cgi/escape, not the full CGI class".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/cgi.rb".freeze,
    "lib/cgi/escape.rb".freeze,
    "lib/cgi/util.rb".freeze,
  ]
end
