# -*- encoding: utf-8 -*-
# stub: date 3.3.4 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "date".freeze
  s.version = "3.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Date and DateTime.  Provided by IronRuby itself.".freeze
  s.summary = "Date and DateTime".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/date.rb".freeze,
    "lib/date/format.rb".freeze,
    "lib/date/delta.rb".freeze,
    "lib/date/delta/parser.rb".freeze,
  ]
end
