# -*- encoding: utf-8 -*-
# stub: did_you_mean 2.0.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "did_you_mean".freeze
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Did you mean? experience.  Provided by IronRuby itself.".freeze
  s.summary = "Did you mean? experience".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/did_you_mean.rb".freeze,
    "lib/did_you_mean/core_ext/name_error.rb".freeze,
    "lib/did_you_mean/experimental.rb".freeze,
    "lib/did_you_mean/formatter.rb".freeze,
    "lib/did_you_mean/formatters/plain_formatter.rb".freeze,
    "lib/did_you_mean/formatters/verbose_formatter.rb".freeze,
    "lib/did_you_mean/jaro_winkler.rb".freeze,
    "lib/did_you_mean/levenshtein.rb".freeze,
    "lib/did_you_mean/spell_checker.rb".freeze,
    "lib/did_you_mean/spell_checkers/key_error_checker.rb".freeze,
    "lib/did_you_mean/spell_checkers/method_name_checker.rb".freeze,
    "lib/did_you_mean/spell_checkers/name_error_checkers.rb".freeze,
    "lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb".freeze,
    "lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb".freeze,
    "lib/did_you_mean/spell_checkers/null_checker.rb".freeze,
    "lib/did_you_mean/spell_checkers/pattern_key_name_checker.rb".freeze,
    "lib/did_you_mean/spell_checkers/require_path_checker.rb".freeze,
    "lib/did_you_mean/tree_spell_checker.rb".freeze,
    "lib/did_you_mean/verbose.rb".freeze,
    "lib/did_you_mean/version.rb".freeze,
  ]
end
