# -*- encoding: utf-8 -*-
# stub: digest 3.2.1 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "digest".freeze
  s.version = "3.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Message digest libraries.  Provided by IronRuby itself.".freeze
  s.summary = "Message digest libraries".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_native".freeze => "true".freeze }
  s.files = [
    "lib/digest.rb".freeze,
    "lib/digest/bubblebabble.rb".freeze,
    "lib/digest/md5.rb".freeze,
    "lib/digest/sha1.rb".freeze,
    "lib/digest/version.rb".freeze,
    "lib/digest/hmac.rb".freeze,
    "lib/digest/sha2.rb".freeze,
  ]
end
