# -*- encoding: utf-8 -*-
# stub: erb 6.0.1.1 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "erb".freeze
  s.version = "6.0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "An easy-to-use but powerful templating system.  Provided by IronRuby itself.".freeze
  s.summary = "An easy-to-use but powerful templating system".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/erb.rb".freeze,
    "lib/erb/compiler.rb".freeze,
    "lib/erb/def_method.rb".freeze,
    "lib/erb/util.rb".freeze,
    "lib/erb/version.rb".freeze,
  ]
end
