# -*- encoding: utf-8 -*-
# stub: error_highlight 0.7.2 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "error_highlight".freeze
  s.version = "0.7.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "The error_highlight API; spot always answers nil here.  Provided by IronRuby itself.".freeze
  s.summary = "The error_highlight API; spot always answers nil here".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/error_highlight.rb".freeze,
    "lib/error_highlight/base.rb".freeze,
    "lib/error_highlight/core_ext.rb".freeze,
    "lib/error_highlight/formatter.rb".freeze,
    "lib/error_highlight/version.rb".freeze,
  ]
end
