# -*- encoding: utf-8 -*-
# stub: fcntl 1.3.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "fcntl".freeze
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Constants for fcntl(2) and open(2).  Provided by IronRuby itself.".freeze
  s.summary = "Constants for fcntl(2) and open(2)".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/fcntl.rb".freeze,
  ]
end
