# -*- encoding: utf-8 -*-
# stub: ffi 1.17.4 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "ffi".freeze
  s.version = "1.17.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "The ffi gem's API, on Fiddle.  Provided by IronRuby itself.".freeze
  s.summary = "The ffi gem's API, on Fiddle".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/ffi.rb".freeze,
    "lib/ffi/abstract_memory.rb".freeze,
    "lib/ffi/autopointer.rb".freeze,
    "lib/ffi/buffer.rb".freeze,
    "lib/ffi/callback.rb".freeze,
    "lib/ffi/compat.rb".freeze,
    "lib/ffi/data_converter.rb".freeze,
    "lib/ffi/dynamic_library.rb".freeze,
    "lib/ffi/enum.rb".freeze,
    "lib/ffi/errno.rb".freeze,
    "lib/ffi/ffi.rb".freeze,
    "lib/ffi/function.rb".freeze,
    "lib/ffi/io.rb".freeze,
    "lib/ffi/ironruby/dynamic_library.rb".freeze,
    "lib/ffi/ironruby/function.rb".freeze,
    "lib/ffi/ironruby/last_error.rb".freeze,
    "lib/ffi/ironruby/memory.rb".freeze,
    "lib/ffi/ironruby/struct.rb".freeze,
    "lib/ffi/ironruby/struct_layout.rb".freeze,
    "lib/ffi/ironruby/type.rb".freeze,
    "lib/ffi/library.rb".freeze,
    "lib/ffi/library_path.rb".freeze,
    "lib/ffi/managedstruct.rb".freeze,
    "lib/ffi/memorypointer.rb".freeze,
    "lib/ffi/platform.rb".freeze,
    "lib/ffi/pointer.rb".freeze,
    "lib/ffi/struct.rb".freeze,
    "lib/ffi/struct_by_reference.rb".freeze,
    "lib/ffi/struct_layout.rb".freeze,
    "lib/ffi/struct_layout_builder.rb".freeze,
    "lib/ffi/tools/const_generator.rb".freeze,
    "lib/ffi/tools/generator.rb".freeze,
    "lib/ffi/tools/generator_task.rb".freeze,
    "lib/ffi/tools/struct_generator.rb".freeze,
    "lib/ffi/types.rb".freeze,
    "lib/ffi/union.rb".freeze,
    "lib/ffi/variadic.rb".freeze,
    "lib/ffi/version.rb".freeze,
  ]
end
