# -*- encoding: utf-8 -*-
# stub: fiddle 1.1.8 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "fiddle".freeze
  s.version = "1.1.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Calling shared-library functions, on NativeLibrary and calli.  Provided by IronRuby itself.".freeze
  s.summary = "Calling shared-library functions, on NativeLibrary and calli".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/fiddle.rb".freeze,
    "lib/fiddle/closure.rb".freeze,
    "lib/fiddle/cparser.rb".freeze,
    "lib/fiddle/function.rb".freeze,
    "lib/fiddle/import.rb".freeze,
    "lib/fiddle/pack.rb".freeze,
    "lib/fiddle/struct.rb".freeze,
    "lib/fiddle/types.rb".freeze,
    "lib/fiddle/value.rb".freeze,
    "lib/fiddle/version.rb".freeze,
  ]
end
