# -*- encoding: utf-8 -*-
# stub: fileutils 1.8.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "fileutils".freeze
  s.version = "1.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Several file utility methods for copying, moving, removing, etc..  Provided by IronRuby itself.".freeze
  s.summary = "Several file utility methods for copying, moving, removing, etc.".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/fileutils.rb".freeze,
  ]
end
