# -*- encoding: utf-8 -*-
# stub: forwardable 1.4.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "forwardable".freeze
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Provides delegation of specified methods to a designated object.  Provided by IronRuby itself.".freeze
  s.summary = "Provides delegation of specified methods to a designated object".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/forwardable.rb".freeze,
  ]
end
