# -*- encoding: utf-8 -*-
# stub: io-console 0.8.2 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "io-console".freeze
  s.version = "0.8.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Console size and raw mode.  Provided by IronRuby itself.".freeze
  s.summary = "Console size and raw mode".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/io/console.rb".freeze,
    "lib/io/console/size.rb".freeze,
  ]
end
