# -*- encoding: utf-8 -*-
# stub: ipaddr 1.2.8 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "ipaddr".freeze
  s.version = "1.2.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "A class to manipulate an IP address.  Provided by IronRuby itself.".freeze
  s.summary = "A class to manipulate an IP address".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/ipaddr.rb".freeze,
  ]
end
