# -*- encoding: utf-8 -*-
# stub: irb 1.16.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "irb".freeze
  s.version = "1.16.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Interactive Ruby.  Provided by IronRuby itself.".freeze
  s.summary = "Interactive Ruby".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.bindir = "exe".freeze
  s.executables = ["irb".freeze]
  s.files = [
    "lib/irb.rb".freeze,
    "lib/irb/cmd/nop.rb".freeze,
    "lib/irb/color.rb".freeze,
    "lib/irb/color_printer.rb".freeze,
    "lib/irb/command.rb".freeze,
    "lib/irb/command/backtrace.rb".freeze,
    "lib/irb/command/base.rb".freeze,
    "lib/irb/command/break.rb".freeze,
    "lib/irb/command/catch.rb".freeze,
    "lib/irb/command/cd.rb".freeze,
    "lib/irb/command/chws.rb".freeze,
    "lib/irb/command/context.rb".freeze,
    "lib/irb/command/continue.rb".freeze,
    "lib/irb/command/copy.rb".freeze,
    "lib/irb/command/debug.rb".freeze,
    "lib/irb/command/delete.rb".freeze,
    "lib/irb/command/disable_irb.rb".freeze,
    "lib/irb/command/edit.rb".freeze,
    "lib/irb/command/exit.rb".freeze,
    "lib/irb/command/finish.rb".freeze,
    "lib/irb/command/force_exit.rb".freeze,
    "lib/irb/command/help.rb".freeze,
    "lib/irb/command/history.rb".freeze,
    "lib/irb/command/info.rb".freeze,
    "lib/irb/command/internal_helpers.rb".freeze,
    "lib/irb/command/irb_info.rb".freeze,
    "lib/irb/command/load.rb".freeze,
    "lib/irb/command/ls.rb".freeze,
    "lib/irb/command/measure.rb".freeze,
    "lib/irb/command/next.rb".freeze,
    "lib/irb/command/pushws.rb".freeze,
    "lib/irb/command/show_doc.rb".freeze,
    "lib/irb/command/show_source.rb".freeze,
    "lib/irb/command/step.rb".freeze,
    "lib/irb/command/subirb.rb".freeze,
    "lib/irb/command/whereami.rb".freeze,
    "lib/irb/completion.rb".freeze,
    "lib/irb/context.rb".freeze,
    "lib/irb/debug.rb".freeze,
    "lib/irb/debug/ui.rb".freeze,
    "lib/irb/default_commands.rb".freeze,
    "lib/irb/easter-egg.rb".freeze,
    "lib/irb/ext/change-ws.rb".freeze,
    "lib/irb/ext/eval_history.rb".freeze,
    "lib/irb/ext/loader.rb".freeze,
    "lib/irb/ext/multi-irb.rb".freeze,
    "lib/irb/ext/tracer.rb".freeze,
    "lib/irb/ext/use-loader.rb".freeze,
    "lib/irb/ext/workspaces.rb".freeze,
    "lib/irb/frame.rb".freeze,
    "lib/irb/help.rb".freeze,
    "lib/irb/helper_method.rb".freeze,
    "lib/irb/helper_method/base.rb".freeze,
    "lib/irb/helper_method/conf.rb".freeze,
    "lib/irb/history.rb".freeze,
    "lib/irb/init.rb".freeze,
    "lib/irb/input-method.rb".freeze,
    "lib/irb/inspector.rb".freeze,
    "lib/irb/lc/error.rb".freeze,
    "lib/irb/lc/ja/error.rb".freeze,
    "lib/irb/locale.rb".freeze,
    "lib/irb/nesting_parser.rb".freeze,
    "lib/irb/notifier.rb".freeze,
    "lib/irb/output-method.rb".freeze,
    "lib/irb/pager.rb".freeze,
    "lib/irb/ruby-lex.rb".freeze,
    "lib/irb/source_finder.rb".freeze,
    "lib/irb/statement.rb".freeze,
    "lib/irb/version.rb".freeze,
    "lib/irb/workspace.rb".freeze,
    "lib/irb/ws-for-case-2.rb".freeze,
    "lib/irb/xmp.rb".freeze,
    "lib/irb/cmd/chws.rb".freeze,
    "lib/irb/cmd/fork.rb".freeze,
    "lib/irb/cmd/help.rb".freeze,
    "lib/irb/cmd/load.rb".freeze,
    "lib/irb/cmd/pushws.rb".freeze,
    "lib/irb/cmd/subirb.rb".freeze,
    "lib/irb/ext/history.rb".freeze,
    "lib/irb/ext/math-mode.rb".freeze,
    "lib/irb/ext/save-history.rb".freeze,
    "lib/irb/extend-command.rb".freeze,
    "lib/irb/lc/ja/encoding_aliases.rb".freeze,
    "lib/irb/magic-file.rb".freeze,
    "lib/irb/ruby-token.rb".freeze,
    "lib/irb/slex.rb".freeze,
    "lib/irb/src_encoding.rb".freeze,
  ]
end
