# -*- encoding: utf-8 -*-
# stub: json 2.18.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "json".freeze
  s.version = "2.18.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "JSON parsing and generation.  Provided by IronRuby itself.".freeze
  s.summary = "JSON parsing and generation".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_native".freeze => "true".freeze }
  s.files = [
    "lib/json.rb".freeze,
    "lib/json/add/core.rb".freeze,
    "lib/json/add/rails.rb".freeze,
    "lib/json/common.rb".freeze,
    "lib/json/editor.rb".freeze,
    "lib/json/ext.rb".freeze,
    "lib/json/version.rb".freeze,
  ]
end
