# -*- encoding: utf-8 -*-
# stub: msgpack 1.8.5 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "msgpack".freeze
  s.version = "1.8.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "MessagePack serialization; the C extension ported to C#.  Provided by IronRuby itself.".freeze
  s.summary = "MessagePack serialization; the C extension ported to C#".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/msgpack.rb".freeze,
    "lib/msgpack/bigint.rb".freeze,
    "lib/msgpack/buffer.rb".freeze,
    "lib/msgpack/core_ext.rb".freeze,
    "lib/msgpack/factory.rb".freeze,
    "lib/msgpack/msgpack.rb".freeze,
    "lib/msgpack/packer.rb".freeze,
    "lib/msgpack/symbol.rb".freeze,
    "lib/msgpack/time.rb".freeze,
    "lib/msgpack/timestamp.rb".freeze,
    "lib/msgpack/unpacker.rb".freeze,
    "lib/msgpack/version.rb".freeze,
  ]
end
