# -*- encoding: utf-8 -*-
# stub: net-http 0.9.1 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "net-http".freeze
  s.version = "0.9.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "HTTP client api for Ruby.  Provided by IronRuby itself.".freeze
  s.summary = "HTTP client api for Ruby".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/net/http.rb".freeze,
    "lib/net/https.rb".freeze,
    "lib/net/http/exceptions.rb".freeze,
    "lib/net/http/generic_request.rb".freeze,
    "lib/net/http/header.rb".freeze,
    "lib/net/http/proxy_delta.rb".freeze,
    "lib/net/http/request.rb".freeze,
    "lib/net/http/requests.rb".freeze,
    "lib/net/http/response.rb".freeze,
    "lib/net/http/responses.rb".freeze,
    "lib/net/http/status.rb".freeze,
  ]
end
