# -*- encoding: utf-8 -*-
# stub: net-protocol 0.2.2 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "net-protocol".freeze
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "The abstract interface for net-* client.  Provided by IronRuby itself.".freeze
  s.summary = "The abstract interface for net-* client".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/net/protocol.rb".freeze,
  ]
end
