# -*- encoding: utf-8 -*-
# stub: nio4r 2.7.5 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "nio4r".freeze
  s.version = "2.7.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "NIO::Selector, Monitor and ByteBuffer, on epoll, poll(2) or Socket.Select.  Provided by IronRuby itself.".freeze
  s.summary = "NIO::Selector, Monitor and ByteBuffer, on epoll, poll(2) or Socket.Select".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/nio.rb".freeze,
    "lib/nio/bytebuffer.rb".freeze,
    "lib/nio/monitor.rb".freeze,
    "lib/nio/selector.rb".freeze,
    "lib/nio/version.rb".freeze,
    "lib/nio4r.rb".freeze,
    "lib/nio4r_ext.rb".freeze,
  ]
end
