# -*- encoding: utf-8 -*-
# stub: nkf 0.2.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "nkf".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Network Kanji Filter, on String#encode.  Provided by IronRuby itself.".freeze
  s.summary = "Network Kanji Filter, on String#encode".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/nkf.rb".freeze,
    "lib/kconv.rb".freeze,
  ]
end
