# -*- encoding: utf-8 -*-
# stub: nokogiri 1.18.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "nokogiri".freeze
  s.version = "1.18.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "HTML5, HTML4 and XML parsing, on AngleSharp.  Provided by IronRuby itself.".freeze
  s.summary = "HTML5, HTML4 and XML parsing, on AngleSharp".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/nokogiri.rb".freeze,
    "lib/nokogiri/css.rb".freeze,
    "lib/nokogiri/html.rb".freeze,
    "lib/nokogiri/serializer.rb".freeze,
    "lib/nokogiri/version.rb".freeze,
    "lib/nokogiri/xml/document.rb".freeze,
    "lib/nokogiri/xml/document_fragment.rb".freeze,
    "lib/nokogiri/xml/node.rb".freeze,
    "lib/nokogiri/xml/node_set.rb".freeze,
    "lib/nokogiri/xpath.rb".freeze,
  ]
end
