# -*- encoding: utf-8 -*-
# stub: oj 3.17.6 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "oj".freeze
  s.version = "3.17.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Oj's :strict, :null, :compat and :rails modes and mimic_JSON, in C#.  Provided by IronRuby itself.".freeze
  s.summary = "Oj's :strict, :null, :compat and :rails modes and mimic_JSON, in C#".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/oj.rb".freeze,
    "lib/oj/active_support_helper.rb".freeze,
    "lib/oj/bag.rb".freeze,
    "lib/oj/easy_hash.rb".freeze,
    "lib/oj/error.rb".freeze,
    "lib/oj/json.rb".freeze,
    "lib/oj/mimic.rb".freeze,
    "lib/oj/oj.rb".freeze,
    "lib/oj/saj.rb".freeze,
    "lib/oj/schandler.rb".freeze,
    "lib/oj/state.rb".freeze,
    "lib/oj/version.rb".freeze,
  ]
end
