# -*- encoding: utf-8 -*-
# stub: openssl 3.2.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "openssl".freeze
  s.version = "3.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "OpenSSL bindings, on .NET's cryptography stack.  Provided by IronRuby itself.".freeze
  s.summary = "OpenSSL bindings, on .NET's cryptography stack".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/openssl.rb".freeze,
    "lib/openssl/asn1.rb".freeze,
    "lib/openssl/bn.rb".freeze,
    "lib/openssl/cipher.rb".freeze,
    "lib/openssl/pkey.rb".freeze,
    "lib/openssl/ssl.rb".freeze,
    "lib/openssl/buffering.rb".freeze,
    "lib/openssl/digest.rb".freeze,
    "lib/openssl/ssl-internal.rb".freeze,
    "lib/openssl/x509-internal.rb".freeze,
    "lib/openssl/x509.rb".freeze,
  ]
end
