# -*- encoding: utf-8 -*-
# stub: open-uri 0.5.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "open-uri".freeze
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "An easy-to-use wrapper for Net::HTTP and Net::FTP.  Provided by IronRuby itself.".freeze
  s.summary = "An easy-to-use wrapper for Net::HTTP and Net::FTP".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/open-uri.rb".freeze,
  ]
end
