# -*- encoding: utf-8 -*-
# stub: optparse 0.8.1 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "optparse".freeze
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "OptionParser is a class for command-line option analysis.  Provided by IronRuby itself.".freeze
  s.summary = "OptionParser is a class for command-line option analysis".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/optparse.rb".freeze,
    "lib/optparse/ac.rb".freeze,
    "lib/optparse/date.rb".freeze,
    "lib/optparse/kwargs.rb".freeze,
    "lib/optparse/shellwords.rb".freeze,
    "lib/optparse/time.rb".freeze,
    "lib/optparse/uri.rb".freeze,
    "lib/optparse/version.rb".freeze,
    "lib/optionparser.rb".freeze,
  ]
end
