# -*- encoding: utf-8 -*-
# stub: prism 1.9.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "prism".freeze
  s.version = "1.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "The Prism Ruby parser - IronRuby's own front end.  Provided by IronRuby itself.".freeze
  s.summary = "The Prism Ruby parser - IronRuby's own front end".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_native".freeze => "true".freeze }
  s.files = [
    "lib/prism.rb".freeze,
    "lib/prism/ironruby.rb".freeze,
    "lib/prism/compiler.rb".freeze,
    "lib/prism/desugar_compiler.rb".freeze,
    "lib/prism/dispatcher.rb".freeze,
    "lib/prism/dot_visitor.rb".freeze,
    "lib/prism/dsl.rb".freeze,
    "lib/prism/ffi.rb".freeze,
    "lib/prism/inspect_visitor.rb".freeze,
    "lib/prism/lex_compat.rb".freeze,
    "lib/prism/mutation_compiler.rb".freeze,
    "lib/prism/node.rb".freeze,
    "lib/prism/node_ext.rb".freeze,
    "lib/prism/node_find.rb".freeze,
    "lib/prism/parse_result.rb".freeze,
    "lib/prism/parse_result/comments.rb".freeze,
    "lib/prism/parse_result/errors.rb".freeze,
    "lib/prism/parse_result/newlines.rb".freeze,
    "lib/prism/pattern.rb".freeze,
    "lib/prism/polyfill/append_as_bytes.rb".freeze,
    "lib/prism/polyfill/byteindex.rb".freeze,
    "lib/prism/polyfill/scan_byte.rb".freeze,
    "lib/prism/polyfill/unpack1.rb".freeze,
    "lib/prism/polyfill/warn.rb".freeze,
    "lib/prism/reflection.rb".freeze,
    "lib/prism/relocation.rb".freeze,
    "lib/prism/serialize.rb".freeze,
    "lib/prism/string_query.rb".freeze,
    "lib/prism/translation.rb".freeze,
    "lib/prism/translation/parser.rb".freeze,
    "lib/prism/translation/parser/builder.rb".freeze,
    "lib/prism/translation/parser/compiler.rb".freeze,
    "lib/prism/translation/parser/lexer.rb".freeze,
    "lib/prism/translation/parser_current.rb".freeze,
    "lib/prism/translation/parser_versions.rb".freeze,
    "lib/prism/translation/ripper.rb".freeze,
    "lib/prism/translation/ripper/filter.rb".freeze,
    "lib/prism/translation/ripper/lexer.rb".freeze,
    "lib/prism/translation/ripper/sexp.rb".freeze,
    "lib/prism/translation/ripper/shim.rb".freeze,
    "lib/prism/translation/ruby_parser.rb".freeze,
    "lib/prism/visitor.rb".freeze,
  ]
end
