# -*- encoding: utf-8 -*-
# stub: psych 5.3.1 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "psych".freeze
  s.version = "5.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "YAML parser and emitter.  Provided by IronRuby itself.".freeze
  s.summary = "YAML parser and emitter".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/psych.rb".freeze,
    "lib/psych/coder.rb".freeze,
    "lib/psych/core_ext.rb".freeze,
    "lib/psych/deprecated.rb".freeze,
    "lib/psych/handler.rb".freeze,
    "lib/psych/json/tree_builder.rb".freeze,
    "lib/psych/nodes.rb".freeze,
    "lib/psych/nodes/alias.rb".freeze,
    "lib/psych/nodes/document.rb".freeze,
    "lib/psych/nodes/mapping.rb".freeze,
    "lib/psych/nodes/node.rb".freeze,
    "lib/psych/nodes/scalar.rb".freeze,
    "lib/psych/nodes/sequence.rb".freeze,
    "lib/psych/nodes/stream.rb".freeze,
    "lib/psych/omap.rb".freeze,
    "lib/psych/parser.rb".freeze,
    "lib/psych/scalar_scanner.rb".freeze,
    "lib/psych/set.rb".freeze,
    "lib/psych/tree_builder.rb".freeze,
    "lib/psych/visitors.rb".freeze,
    "lib/psych/visitors/emitter.rb".freeze,
    "lib/psych/visitors/json_tree.rb".freeze,
    "lib/psych/visitors/to_ruby.rb".freeze,
    "lib/psych/visitors/visitor.rb".freeze,
    "lib/psych/visitors/yaml_tree.rb".freeze,
  ]
end
