# -*- encoding: utf-8 -*-
# stub: puma 8.0.2 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "puma".freeze
  s.version = "8.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Puma, with its HTTP parser in C#; single mode only, no TLS.  Provided by IronRuby itself.".freeze
  s.summary = "Puma, with its HTTP parser in C#; single mode only, no TLS".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.bindir = "exe".freeze
  s.executables = ["puma".freeze, "pumactl".freeze]
  s.files = [
    "lib/puma.rb".freeze,
    "lib/puma/app/status.rb".freeze,
    "lib/puma/binder.rb".freeze,
    "lib/puma/cli.rb".freeze,
    "lib/puma/client.rb".freeze,
    "lib/puma/client_env.rb".freeze,
    "lib/puma/cluster.rb".freeze,
    "lib/puma/cluster/worker.rb".freeze,
    "lib/puma/cluster/worker_handle.rb".freeze,
    "lib/puma/cluster_accept_loop_delay.rb".freeze,
    "lib/puma/commonlogger.rb".freeze,
    "lib/puma/configuration.rb".freeze,
    "lib/puma/const.rb".freeze,
    "lib/puma/control_cli.rb".freeze,
    "lib/puma/detect.rb".freeze,
    "lib/puma/dsl.rb".freeze,
    "lib/puma/error_logger.rb".freeze,
    "lib/puma/events.rb".freeze,
    "lib/puma/io_buffer.rb".freeze,
    "lib/puma/jruby_restart.rb".freeze,
    "lib/puma/json_serialization.rb".freeze,
    "lib/puma/launcher.rb".freeze,
    "lib/puma/launcher/bundle_pruner.rb".freeze,
    "lib/puma/log_writer.rb".freeze,
    "lib/puma/minissl.rb".freeze,
    "lib/puma/minissl/context_builder.rb".freeze,
    "lib/puma/null_io.rb".freeze,
    "lib/puma/plugin.rb".freeze,
    "lib/puma/plugin/systemd.rb".freeze,
    "lib/puma/plugin/tmp_restart.rb".freeze,
    "lib/puma/puma_http11.rb".freeze,
    "lib/puma/rack/builder.rb".freeze,
    "lib/puma/rack/urlmap.rb".freeze,
    "lib/puma/rack_default.rb".freeze,
    "lib/puma/reactor.rb".freeze,
    "lib/puma/response.rb".freeze,
    "lib/puma/runner.rb".freeze,
    "lib/puma/sd_notify.rb".freeze,
    "lib/puma/server.rb".freeze,
    "lib/puma/server_plugin_control.rb".freeze,
    "lib/puma/single.rb".freeze,
    "lib/puma/state_file.rb".freeze,
    "lib/puma/thread_pool.rb".freeze,
    "lib/puma/util.rb".freeze,
    "lib/rack/handler/puma.rb".freeze,
  ]
  s.add_runtime_dependency "nio4r".freeze, ["~> 2.0".freeze]
end
