# -*- encoding: utf-8 -*-
# stub: reline 0.6.3 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "reline".freeze
  s.version = "0.6.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "GNU Readline and Editline, in pure Ruby.  Provided by IronRuby itself.".freeze
  s.summary = "GNU Readline and Editline, in pure Ruby".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/reline.rb".freeze,
    "lib/reline/config.rb".freeze,
    "lib/reline/face.rb".freeze,
    "lib/reline/history.rb".freeze,
    "lib/reline/io.rb".freeze,
    "lib/reline/io/ansi.rb".freeze,
    "lib/reline/io/dumb.rb".freeze,
    "lib/reline/io/windows.rb".freeze,
    "lib/reline/key_actor.rb".freeze,
    "lib/reline/key_actor/base.rb".freeze,
    "lib/reline/key_actor/composite.rb".freeze,
    "lib/reline/key_actor/emacs.rb".freeze,
    "lib/reline/key_actor/vi_command.rb".freeze,
    "lib/reline/key_actor/vi_insert.rb".freeze,
    "lib/reline/key_stroke.rb".freeze,
    "lib/reline/kill_ring.rb".freeze,
    "lib/reline/line_editor.rb".freeze,
    "lib/reline/unicode.rb".freeze,
    "lib/reline/unicode/east_asian_width.rb".freeze,
    "lib/reline/version.rb".freeze,
  ]
end
