# -*- encoding: utf-8 -*-
# stub: resolv 0.7.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "resolv".freeze
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Thread-aware DNS resolver library.  Provided by IronRuby itself.".freeze
  s.summary = "Thread-aware DNS resolver library".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/resolv.rb".freeze,
  ]
end
