# -*- encoding: utf-8 -*-
# stub: ruby2_keywords 0.0.5 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "ruby2_keywords".freeze
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Shim library for Module#ruby2_keywords.  Provided by IronRuby itself.".freeze
  s.summary = "Shim library for Module#ruby2_keywords".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/ruby2_keywords.rb".freeze,
  ]
end
