# -*- encoding: utf-8 -*-
# stub: shellwords 0.2.2 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "shellwords".freeze
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Manipulates strings with word parsing rules of UNIX Bourne shell.  Provided by IronRuby itself.".freeze
  s.summary = "Manipulates strings with word parsing rules of UNIX Bourne shell".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/shellwords.rb".freeze,
  ]
end
