# -*- encoding: utf-8 -*-
# stub: sqlite3 2.9.6 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "sqlite3".freeze
  s.version = "2.9.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "SQLite3, on the native library Microsoft.Data.Sqlite carries.  Provided by IronRuby itself.".freeze
  s.summary = "SQLite3, on the native library Microsoft.Data.Sqlite carries".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_native".freeze => "true".freeze }
  s.files = [
    "lib/sqlite3.rb".freeze,
    "lib/sqlite3/constants.rb".freeze,
    "lib/sqlite3/database.rb".freeze,
    "lib/sqlite3/errors.rb".freeze,
    "lib/sqlite3/fork_safety.rb".freeze,
    "lib/sqlite3/pragmas.rb".freeze,
    "lib/sqlite3/resultset.rb".freeze,
    "lib/sqlite3/statement.rb".freeze,
    "lib/sqlite3/value.rb".freeze,
    "lib/sqlite3/version_info.rb".freeze,
  ]
end
