# -*- encoding: utf-8 -*-
# stub: strscan 3.1.6 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "strscan".freeze
  s.version = "3.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Lexical scanning of strings.  Provided by IronRuby itself.".freeze
  s.summary = "Lexical scanning of strings".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/strscan.rb".freeze,
  ]
end
