# -*- encoding: utf-8 -*-
# stub: syntax_suggest 2.0.3 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "syntax_suggest".freeze
  s.version = "2.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Find syntax errors in your source in a snap.  Provided by IronRuby itself.".freeze
  s.summary = "Find syntax errors in your source in a snap".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/syntax_suggest.rb".freeze,
    "lib/syntax_suggest/api.rb".freeze,
    "lib/syntax_suggest/around_block_scan.rb".freeze,
    "lib/syntax_suggest/block_expand.rb".freeze,
    "lib/syntax_suggest/capture/before_after_keyword_ends.rb".freeze,
    "lib/syntax_suggest/capture/falling_indent_lines.rb".freeze,
    "lib/syntax_suggest/capture_code_context.rb".freeze,
    "lib/syntax_suggest/clean_document.rb".freeze,
    "lib/syntax_suggest/cli.rb".freeze,
    "lib/syntax_suggest/code_block.rb".freeze,
    "lib/syntax_suggest/code_frontier.rb".freeze,
    "lib/syntax_suggest/code_line.rb".freeze,
    "lib/syntax_suggest/code_search.rb".freeze,
    "lib/syntax_suggest/core_ext.rb".freeze,
    "lib/syntax_suggest/display_code_with_line_numbers.rb".freeze,
    "lib/syntax_suggest/display_invalid_blocks.rb".freeze,
    "lib/syntax_suggest/explain_syntax.rb".freeze,
    "lib/syntax_suggest/left_right_lex_count.rb".freeze,
    "lib/syntax_suggest/lex_all.rb".freeze,
    "lib/syntax_suggest/lex_value.rb".freeze,
    "lib/syntax_suggest/mini_stringio.rb".freeze,
    "lib/syntax_suggest/parse_blocks_from_indent_line.rb".freeze,
    "lib/syntax_suggest/pathname_from_message.rb".freeze,
    "lib/syntax_suggest/priority_engulf_queue.rb".freeze,
    "lib/syntax_suggest/priority_queue.rb".freeze,
    "lib/syntax_suggest/ripper_errors.rb".freeze,
    "lib/syntax_suggest/scan_history.rb".freeze,
    "lib/syntax_suggest/unvisited_lines.rb".freeze,
    "lib/syntax_suggest/version.rb".freeze,
  ]
end
