# -*- encoding: utf-8 -*-
# stub: syslog 0.3.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "syslog".freeze
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Syslog, implemented in Src/Libraries/Syslog.  Provided by IronRuby itself.".freeze
  s.summary = "Syslog, implemented in Src/Libraries/Syslog".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/syslog.rb".freeze,
  ]
end
