# -*- encoding: utf-8 -*-
# stub: timeout 0.6.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "timeout".freeze
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Auto-terminate potentially long-running operations.  Provided by IronRuby itself.".freeze
  s.summary = "Auto-terminate potentially long-running operations".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/timeout.rb".freeze,
  ]
end
