# -*- encoding: utf-8 -*-
# stub: time 0.4.2 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "time".freeze
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Extends the Time class with methods for parsing and conversion.  Provided by IronRuby itself.".freeze
  s.summary = "Extends the Time class with methods for parsing and conversion".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/time.rb".freeze,
  ]
end
