# -*- encoding: utf-8 -*-
# stub: tmpdir 0.3.1 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "tmpdir".freeze
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Extends the Dir class to manage the OS temporary file path.  Provided by IronRuby itself.".freeze
  s.summary = "Extends the Dir class to manage the OS temporary file path".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/tmpdir.rb".freeze,
  ]
end
