# -*- encoding: utf-8 -*-
# stub: tsort 0.2.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "tsort".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Topological sorting using Tarjan's algorithm.  Provided by IronRuby itself.".freeze
  s.summary = "Topological sorting using Tarjan's algorithm".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/tsort.rb".freeze,
  ]
end
