# -*- encoding: utf-8 -*-
# stub: un 0.3.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "un".freeze
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Utilities to replace common UNIX commands.  Provided by IronRuby itself.".freeze
  s.summary = "Utilities to replace common UNIX commands".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/un.rb".freeze,
  ]
end
