# -*- encoding: utf-8 -*-
# stub: uri 1.1.1 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "uri".freeze
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "URI is a module providing classes to handle Uniform Resource Identifiers.  Provided by IronRuby itself.".freeze
  s.summary = "URI is a module providing classes to handle Uniform Resource Identifiers".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/uri.rb".freeze,
    "lib/uri/common.rb".freeze,
    "lib/uri/file.rb".freeze,
    "lib/uri/ftp.rb".freeze,
    "lib/uri/generic.rb".freeze,
    "lib/uri/http.rb".freeze,
    "lib/uri/https.rb".freeze,
    "lib/uri/ldap.rb".freeze,
    "lib/uri/ldaps.rb".freeze,
    "lib/uri/mailto.rb".freeze,
    "lib/uri/rfc2396_parser.rb".freeze,
    "lib/uri/rfc3986_parser.rb".freeze,
    "lib/uri/version.rb".freeze,
    "lib/uri/ws.rb".freeze,
    "lib/uri/wss.rb".freeze,
  ]
end
