# -*- encoding: utf-8 -*-
# stub: weakref 0.1.4 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "weakref".freeze
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "Allows a referenced object to be garbage-collected.  Provided by IronRuby itself.".freeze
  s.summary = "Allows a referenced object to be garbage-collected".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/weakref.rb".freeze,
  ]
end
