# -*- encoding: utf-8 -*-
# stub: websocket-driver 0.8.2 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "websocket-driver".freeze
  s.version = "0.8.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "WebSocket protocol handler; WebSocket::Mask in C#.  Provided by IronRuby itself.".freeze
  s.summary = "WebSocket protocol handler; WebSocket::Mask in C#".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.metadata = { "ironruby_pinned".freeze => "true".freeze }
  s.files = [
    "lib/websocket_mask.rb".freeze,
    "lib/websocket/driver.rb".freeze,
    "lib/websocket/driver/client.rb".freeze,
    "lib/websocket/driver/draft75.rb".freeze,
    "lib/websocket/driver/draft76.rb".freeze,
    "lib/websocket/driver/event_emitter.rb".freeze,
    "lib/websocket/driver/headers.rb".freeze,
    "lib/websocket/driver/hybi.rb".freeze,
    "lib/websocket/driver/hybi/frame.rb".freeze,
    "lib/websocket/driver/hybi/message.rb".freeze,
    "lib/websocket/driver/proxy.rb".freeze,
    "lib/websocket/driver/server.rb".freeze,
    "lib/websocket/driver/stream_reader.rb".freeze,
    "lib/websocket/http.rb".freeze,
    "lib/websocket/http/headers.rb".freeze,
    "lib/websocket/http/request.rb".freeze,
    "lib/websocket/http/response.rb".freeze,
    "lib/websocket/mask.rb".freeze,
    "lib/websocket/websocket_mask.rb".freeze,
  ]

  s.add_runtime_dependency("websocket-extensions".freeze, [">= 0.1.0".freeze])
end
