# -*- encoding: utf-8 -*-
# stub: yaml 0.4.0 ruby lib
#
# Generated by Util/gen-default-gemspecs.rb.  Do not edit by hand.

Gem::Specification.new do |s|
  s.name = "yaml".freeze
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze)
  s.require_paths = ["lib".freeze]
  s.authors = ["IronRuby".freeze]
  s.description = "YAML Ain't Markup Language.  Provided by IronRuby itself.".freeze
  s.summary = "YAML Ain't Markup Language".freeze
  s.homepage = "https://github.com/IronLanguages/ironruby".freeze
  s.licenses = ["Ruby".freeze, "BSD-2-Clause".freeze]
  s.files = [
    "lib/yaml.rb".freeze,
    "lib/yaml/types.rb".freeze,
    "lib/yaml/dbm.rb".freeze,
    "lib/yaml/store.rb".freeze,
    "lib/yaml/syck.rb".freeze,
  ]
end
