#!/usr/bin/env ruby
# Generates Src/Ruby/Builtins/UnicodeProperties.Generated.cs: the code-point range
# tables of every character property Onigmo knows (\p{Emoji}, \p{Han}, \p{In_Greek},
# \p{Age=6.0}, [[:alpha:]], ...), for the Onigmo -> .NET regex translation in
# RegexpTransformer.cs. .NET's regex engine knows only the general categories and a
# fixed list of BMP blocks, so the rest are spelled out as explicit ranges.
#
#   ruby Util/gen-unicode-properties.rb [path/to/name2ctype.h] [output.cs]
#
# The input is CRuby's enc/unicode/<version>/name2ctype.h, the table Onigmo is compiled
# with. CRuby's tool/enc-unicode.rb builds it from the Unicode Character Database files
# of that version (UnicodeData.txt, Scripts.txt, ScriptExtensions.txt, PropList.txt,
# DerivedCoreProperties.txt, DerivedAge.txt, Blocks.txt, PropertyValueAliases.txt,
# GraphemeBreakProperty.txt, emoji-data.txt, ...), so reading the ranges from there gives
# exactly the property set and the name aliases CRuby matches with - reading the UCD
# files again would have to reproduce enc-unicode.rb's choices (which aliases, which
# POSIX definitions) and could only drift from it. Re-run when the oracle CRuby moves to
# a new Unicode version; `ruby -e 'p RbConfig::CONFIG["UNICODE_VERSION"]'` says which.
#
# The ranges are stored as a base64 string of LEB128 deltas - about a fifth of the size
# of an int[] initializer, and the IL for a string constant costs nothing to load - and
# decoded one property at a time on first use.

require "base64"

src = ARGV[0] || "/root/workspace/cosmoruby-upgrade/ruby-4.0.6/enc/unicode/17.0.0/name2ctype.h"
out = ARGV[1] || File.expand_path("../Src/Ruby/Builtins/UnicodeProperties.Generated.cs", __dir__)

DEFINED = %w[USE_UNICODE_PROPERTIES USE_UNICODE_AGE_PROPERTIES]

# A minimal preprocessor: the two feature macros CRuby defines are on, every other
# #if (the gperf character-set check, the version-mismatch #error) is off.
lines = []
stack = []
File.foreach(src) do |line|
  case line
  when /^#\s*ifdef\s+(\w+)/  then stack << DEFINED.include?($1)
  when /^#\s*ifndef\s+(\w+)/ then stack << !DEFINED.include?($1)
  when /^#\s*if\b/           then stack << false
  when /^#\s*else\b/         then stack[-1] = !stack[-1]
  when /^#\s*endif\b/        then stack.pop
  else lines << line if stack.all?
  end
end
text = lines.join

unicode_version = src[%r{/(\d+\.\d+\.\d+)/name2ctype\.h\z}, 1] or abort "no Unicode version in #{src}"
emoji_version = File.read(src)[/#define ONIG_UNICODE_EMOJI_VERSION_STRING "([^"]+)"/, 1]

# CR_Name[] = { count, lo, hi, ... };
arrays = {}
text.scan(/static const OnigCodePoint (CR_\w+)\[\] = \{(.*?)\};/m) do |name, body|
  values = body.scan(/0x\h+|\d+/).map { |v| Integer(v) }
  count = values.shift
  raise "#{name}: #{values.size} values for #{count} ranges" unless values.size == count * 2
  arrays[name] = values
end
aliases = text.scan(/^#define (CR_\w+) (CR_\w+)$/).to_h
resolve = ->(n) { n = aliases[n] while aliases.key?(n); n }

ctypes = text[/CodeRanges\[\] = \{(.*?)\};/m, 1].scan(/CR_\w+/).map { |n| resolve.(n) }
ctypes.each { |n| raise "unknown #{n}" unless arrays.key?(n) }

pool = text[/struct uniname2ctype_pool_t\s*\{(.*?)\};/m, 1]
strs = pool.scan(/uniname2ctype_pool_(str\d+)\[sizeof\("([^"]*)"\)\]/).to_h
words = text[/wordlist\[\] =\s*\{(.*?)\};/m, 1]
names = {}
words.scan(/uniname2ctype_offset\((str\d+)\),\s*(\d+)/) do |str, ctype|
  name = strs.fetch(str)
  raise "duplicate #{name}" if names.key?(name)
  names[name] = ctypes.fetch(Integer(ctype))
end

# The POSIX bracket classes use Onigmo's ctype numbers (ONIGENC_CTYPE_ALPHA = 1 ...
# ONIGENC_CTYPE_ASCII = 14), which are not always what the same name means in \p{...}:
# [[:punct:]] is CR_XPosixPunct (it takes in $+<=>^`|~), \p{Punct} is CR_Punct.
POSIX = %w[alpha blank cntrl digit graph lower print punct space upper xdigit word alnum ascii]
posix = POSIX.each_with_index.map { |n, i| [n, ctypes.fetch(i + 1)] }.to_h

# One table per distinct range list, in first-use order.
tables = (names.values + posix.values).uniq.sort_by { |n| ctypes.index(n) }
table_index = tables.each_with_index.to_h

def leb128(n, bytes)
  loop do
    b = n & 0x7f
    n >>= 7
    bytes << (n.zero? ? b : b | 0x80)
    break if n.zero?
  end
end

bytes = []
offsets = []
tables.each do |t|
  offsets << bytes.size
  ranges = arrays.fetch(t)
  leb128(ranges.size / 2, bytes)
  prev = -1
  ranges.each_slice(2) do |lo, hi|
    raise "#{t}: unsorted" unless lo > prev && hi >= lo
    leb128(lo - prev - 1, bytes)
    leb128(hi - lo, bytes)
    prev = hi
  end
end
offsets << bytes.size

data = Base64.strict_encode64(bytes.pack("C*"))
sorted = names.keys.sort

cs = +""
cs << "// <auto-generated> generated by Util/gen-unicode-properties.rb from CRuby's " \
      "enc/unicode/#{unicode_version}/name2ctype.h - do not edit </auto-generated>\r\n"
cs << "namespace IronRuby.Builtins {\r\n"
cs << "    internal static partial class UnicodeProperties {\r\n"
cs << "        internal const string UnicodeVersion = \"#{unicode_version}\";\r\n"
cs << "        internal const string EmojiVersion = \"#{emoji_version}\";\r\n\r\n"
cs << "        // Every property name Onigmo accepts, normalized the way it compares them (lower case,\r\n"
cs << "        // no ' ', '-' or '_'), sorted ordinally; _nameTables[i] is the table _names[i] selects.\r\n"
cs << "        private static readonly string[] _names = new string[] {\r\n"
sorted.each_slice(8) { |s| cs << "            " << s.map { |n| "\"#{n}\"" }.join(", ") << ",\r\n" }
cs << "        };\r\n\r\n"
cs << "        private static readonly ushort[] _nameTables = new ushort[] {\r\n"
sorted.map { |n| table_index.fetch(names[n]) }.each_slice(16) { |s| cs << "            " << s.join(", ") << ",\r\n" }
cs << "        };\r\n\r\n"
cs << "        // The POSIX bracket names ([[:alpha:]]), sorted, and the table each selects.\r\n"
cs << "        private static readonly string[] _posixNames = new string[] {\r\n"
cs << "            " << POSIX.sort.map { |n| "\"#{n}\"" }.join(", ") << ",\r\n"
cs << "        };\r\n\r\n"
cs << "        private static readonly ushort[] _posixTables = new ushort[] {\r\n"
cs << "            " << POSIX.sort.map { |n| table_index.fetch(posix[n]) }.join(", ") << ",\r\n"
cs << "        };\r\n\r\n"
cs << "        // Onigmo's name for each table (CR_...), for diagnostics.\r\n"
cs << "        private static readonly string[] _tableNames = new string[] {\r\n"
tables.each_slice(6) { |s| cs << "            " << s.map { |n| "\"#{n}\"" }.join(", ") << ",\r\n" }
cs << "        };\r\n\r\n"
cs << "        // Byte offset of each table in _data, and the end of the last one.\r\n"
cs << "        private static readonly int[] _offsets = new int[] {\r\n"
offsets.each_slice(12) { |s| cs << "            " << s.join(", ") << ",\r\n" }
cs << "        };\r\n\r\n"
cs << "        // Per table: the range count, then for each range the gap from the previous range's end\r\n"
cs << "        // (minus one) and the range's length (minus one), all as LEB128 varints; base64.\r\n"
cs << "        private const string _data =\r\n"
chunks = data.scan(/.{1,120}/)
chunks.each_with_index { |c, i| cs << "            \"#{c}\"" << (i == chunks.size - 1 ? ";\r\n" : " +\r\n") }
cs << "    }\r\n"
cs << "}\r\n"

File.binwrite(out, cs)
warn "#{names.size} names, #{tables.size} tables, #{arrays.values.sum { |a| a.size / 2 }} ranges, " \
     "#{bytes.size} bytes -> #{out}"
