<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ClassInitGenerator</AssemblyName>
    <RootNamespace>ClassInitGenerator</RootNamespace>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS0618;SYSLIB0012</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ruby\Ruby.csproj" />
    <ProjectReference Include="..\Libraries\IronRuby.Libraries.csproj" />
    <ProjectReference Include="..\Libraries.Yaml\IronRuby.Libraries.Yaml.csproj" />
    <ProjectReference Include="$(DlrSourceDir)\Microsoft.Scripting\Microsoft.Scripting.csproj" />
    <ProjectReference Include="$(DlrSourceDir)\Microsoft.Dynamic\Microsoft.Dynamic.csproj" />
  </ItemGroup>
</Project>
