#!/usr/bin/env ruby
# Generates typed C# node classes and a binary-serialization loader from
# prism's config.yml — the same approach JRuby uses for its Java loader.
#
#   ruby generate.rb [path/to/prism/config.yml] [output-dir]
#
# Re-run when upgrading the vendored prism (the loader validates the
# serialization version at runtime, so drift fails loudly).
require "yaml"

config_path = ARGV[0] || File.expand_path("../../../prism/config.yml", __dir__)
out_dir = ARGV[1] || File.expand_path("Generated", __dir__)
config = YAML.load_file(config_path)
nodes = config.fetch("nodes")
flags = config.fetch("flags")

def pascal(name)
  name.split("_").map(&:capitalize).join
end

def cs_type(field)
  case field.fetch("type")
  when "node" then "PmNode"
  when "node?" then "PmNode"
  when "node[]" then "PmNode[]"
  when "string" then "string"
  when "constant" then "string"
  when "constant?" then "string"
  when "constant[]" then "string[]"
  when "location" then "PmLocation"
  when "location?" then "PmLocation?"
  when "uint8" then "byte"
  when "uint32" then "uint"
  when "integer" then "System.Numerics.BigInteger"
  when "double" then "double"
  else raise "unknown field type #{field["type"]}"
  end
end

def cs_reader(field)
  case field.fetch("type")
  when "node" then "LoadNode()"
  when "node?" then "LoadOptionalNode()"
  when "node[]" then "LoadNodeList()"
  when "string" then "LoadString()"
  when "constant" then "LoadConstant()"
  when "constant?" then "LoadOptionalConstant()"
  when "constant[]" then "LoadConstantList()"
  when "location" then "LoadLocation()"
  when "location?" then "LoadOptionalLocation()"
  when "uint8" then "LoadByte()"
  when "uint32" then "LoadVarUInt()"
  when "integer" then "LoadInteger()"
  when "double" then "LoadDouble()"
  end
end

def field_name(node, field)
  name = pascal(field.fetch("name"))
  name == node.fetch("name") ? name + "Field" : name
end

require "stringio"

# ---- PrismNodes.Generated.cs ----
nodes_cs = StringIO.new
nodes_cs << <<~CS
  // <auto-generated> generated by generate.rb from prism config.yml — do not edit </auto-generated>
  namespace IronRuby.Prism.Ast {
      public readonly struct PmLocation {
          public readonly int Start;
          public readonly int Length;
          public PmLocation(int start, int length) { Start = start; Length = length; }
      }

      public abstract class PmNode {
          public uint NodeId;
          public int StartOffset;
          public int Length;
          public uint Flags;

          // common flags (bits 0-1); node-specific flags start at bit 2
          public bool IsNewLine { get { return (Flags & 1u) != 0; } }
          public bool IsStaticLiteral { get { return (Flags & 2u) != 0; } }
      }

CS
flags.each do |flag_set|
  nodes_cs << "    public static class #{flag_set.fetch("name")} {\n"
  flag_set.fetch("values").each_with_index do |value, i|
    nodes_cs << "        public const uint #{pascal(value.fetch("name").downcase)} = 1u << #{i + 2};\n"
  end
  nodes_cs << "    }\n\n"
end
nodes.each do |node|
  nodes_cs << "    public sealed class #{node.fetch("name")} : PmNode {\n"
  (node["fields"] || []).each do |field|
    nodes_cs << "        public #{cs_type(field)} #{field_name(node, field)};\n"
  end
  nodes_cs << "    }\n\n"
end
nodes_cs << "}\n"

# ---- PrismLoader.Generated.cs ----
loader_cs = StringIO.new
loader_cs << <<~CS
  // <auto-generated> generated by generate.rb from prism config.yml — do not edit </auto-generated>
  using IronRuby.Prism.Ast;

  namespace IronRuby.Prism {
      public sealed partial class PrismLoader {
          public const int SerializationMajor = #{`grep -m1 "PRISM_VERSION_MAJOR" #{File.dirname(config_path)}/include/prism/version.h`[/\d+/]};
          public const int SerializationMinor = #{`grep -m1 "PRISM_VERSION_MINOR" #{File.dirname(config_path)}/include/prism/version.h`[/\d+/]};
          public const int SerializationPatch = #{`grep -m1 "PRISM_VERSION_PATCH" #{File.dirname(config_path)}/include/prism/version.h`[/\d+/]};

          private PmNode LoadNode() {
              byte type = LoadByte();
              uint nodeId = LoadVarUInt();
              PmLocation location = LoadLocation();
              switch (type) {
CS
nodes.each_with_index do |node, index|
  loader_cs << "                case #{index + 1}: {\n"
  loader_cs << "                    LoadRawUInt32();\n" if node.fetch("name") == "DefNode"
  loader_cs << "                    return new #{node.fetch("name")} {\n"
  loader_cs << "                        NodeId = nodeId, StartOffset = location.Start, Length = location.Length,\n"
  loader_cs << "                        Flags = LoadVarUInt(),\n"
  (node["fields"] || []).each do |field|
    loader_cs << "                        #{field_name(node, field)} = #{cs_reader(field)},\n"
  end
  loader_cs << "                    };\n"
  loader_cs << "                }\n"
end
loader_cs << <<~CS
                default:
                    throw new System.InvalidOperationException("Unknown prism node type: " + type);
            }
        }
    }
  }
CS

Dir.mkdir(out_dir) unless Dir.exist?(out_dir)
File.write(File.join(out_dir, "PrismNodes.Generated.cs"), nodes_cs.string)
File.write(File.join(out_dir, "PrismLoader.Generated.cs"), loader_cs.string)
puts "generated #{nodes.size} node classes, #{flags.size} flag sets -> #{out_dir}"
