<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>IronRuby.Prism</AssemblyName>
    <RootNamespace>IronRuby.Prism</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <!-- built from ../../../prism with `ruby templates/template.rb && make shared` -->
    <Content Include="$(MSBuildThisFileDirectory)..\..\..\prism\build\libprism.so" Condition="Exists('$(MSBuildThisFileDirectory)..\..\..\prism\build\libprism.so')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libprism.so</Link>
    </Content>
  </ItemGroup>
</Project>
